package hibernatetest;
// Generated Jun 11, 2018 9:17:13 PM by Hibernate Tools 4.3.1



/**
 * Owner generated by hbm2java
 */
public class Owner  implements java.io.Serializable {


     private int idowner;
     private String oname;
     private String ophone;
     private String oemail;

    public Owner() {
    }

	
    public Owner(int idowner) {
        this.idowner = idowner;
    }
    public Owner(int idowner, String oname, String ophone, String oemail) {
       this.idowner = idowner;
       this.oname = oname;
       this.ophone = ophone;
       this.oemail = oemail;
    }
   
    public int getIdowner() {
        return this.idowner;
    }
    
    public void setIdowner(int idowner) {
        this.idowner = idowner;
    }
    public String getOname() {
        return this.oname;
    }
    
    public void setOname(String oname) {
        this.oname = oname;
    }
    public String getOphone() {
        return this.ophone;
    }
    
    public void setOphone(String ophone) {
        this.ophone = ophone;
    }
    public String getOemail() {
        return this.oemail;
    }
    
    public void setOemail(String oemail) {
        this.oemail = oemail;
    }




}


